//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34014
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace FukjTabletSystem.Application.Boundary.MapWorks {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("MapPointDataSet")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class MapPointDataSet : global::System.Data.DataSet {
        
        private JokasoMapPointDataTable tableJokasoMapPoint;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public MapPointDataSet() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected MapPointDataSet(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["JokasoMapPoint"] != null)) {
                    base.Tables.Add(new JokasoMapPointDataTable(ds.Tables["JokasoMapPoint"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public JokasoMapPointDataTable JokasoMapPoint {
            get {
                return this.tableJokasoMapPoint;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public override global::System.Data.DataSet Clone() {
            MapPointDataSet cln = ((MapPointDataSet)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["JokasoMapPoint"] != null)) {
                    base.Tables.Add(new JokasoMapPointDataTable(ds.Tables["JokasoMapPoint"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        internal void InitVars(bool initTable) {
            this.tableJokasoMapPoint = ((JokasoMapPointDataTable)(base.Tables["JokasoMapPoint"]));
            if ((initTable == true)) {
                if ((this.tableJokasoMapPoint != null)) {
                    this.tableJokasoMapPoint.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void InitClass() {
            this.DataSetName = "MapPointDataSet";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/MapPointDataSet.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableJokasoMapPoint = new JokasoMapPointDataTable();
            base.Tables.Add(this.tableJokasoMapPoint);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private bool ShouldSerializeJokasoMapPoint() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            MapPointDataSet ds = new MapPointDataSet();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public delegate void JokasoMapPointRowChangeEventHandler(object sender, JokasoMapPointRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class JokasoMapPointDataTable : global::System.Data.TypedTableBase<JokasoMapPointRow> {
            
            private global::System.Data.DataColumn columnKensaIraiHoteiKbn;
            
            private global::System.Data.DataColumn columnKensaIraiHokenjoCd;
            
            private global::System.Data.DataColumn columnKensaIraiNendo;
            
            private global::System.Data.DataColumn columnKensaIraiRenban;
            
            private global::System.Data.DataColumn columnKensaIraiRowIndex;
            
            private global::System.Data.DataColumn columnJokasoSetchishaNm;
            
            private global::System.Data.DataColumn columnJokasoSetchiBashoAdr;
            
            private global::System.Data.DataColumn columnKensaKekkaKensaJoukyouKbn;
            
            private global::System.Data.DataColumn columnJokasoZenrinKeidoCd;
            
            private global::System.Data.DataColumn columnJokasoZenrinIdoCd;
            
            private global::System.Data.DataColumn columnMapPointStatusObjectID;
            
            private global::System.Data.DataColumn columnMapPointInfoObjectID;
            
            private global::System.Data.DataColumn columnMapPointSeqObjectID;
            
            private global::System.Data.DataColumn columnMapPointSeqObjectID_backcolor;
            
            private global::System.Data.DataColumn columnMapPointX;
            
            private global::System.Data.DataColumn columnMapPointY;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public JokasoMapPointDataTable() {
                this.TableName = "JokasoMapPoint";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal JokasoMapPointDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected JokasoMapPointDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn KensaIraiHoteiKbnColumn {
                get {
                    return this.columnKensaIraiHoteiKbn;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn KensaIraiHokenjoCdColumn {
                get {
                    return this.columnKensaIraiHokenjoCd;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn KensaIraiNendoColumn {
                get {
                    return this.columnKensaIraiNendo;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn KensaIraiRenbanColumn {
                get {
                    return this.columnKensaIraiRenban;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn KensaIraiRowIndexColumn {
                get {
                    return this.columnKensaIraiRowIndex;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn JokasoSetchishaNmColumn {
                get {
                    return this.columnJokasoSetchishaNm;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn JokasoSetchiBashoAdrColumn {
                get {
                    return this.columnJokasoSetchiBashoAdr;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn KensaKekkaKensaJoukyouKbnColumn {
                get {
                    return this.columnKensaKekkaKensaJoukyouKbn;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn JokasoZenrinKeidoCdColumn {
                get {
                    return this.columnJokasoZenrinKeidoCd;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn JokasoZenrinIdoCdColumn {
                get {
                    return this.columnJokasoZenrinIdoCd;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn MapPointStatusObjectIDColumn {
                get {
                    return this.columnMapPointStatusObjectID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn MapPointInfoObjectIDColumn {
                get {
                    return this.columnMapPointInfoObjectID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn MapPointSeqObjectIDColumn {
                get {
                    return this.columnMapPointSeqObjectID;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn MapPointSeqObjectID_backcolorColumn {
                get {
                    return this.columnMapPointSeqObjectID_backcolor;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn MapPointXColumn {
                get {
                    return this.columnMapPointX;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn MapPointYColumn {
                get {
                    return this.columnMapPointY;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public JokasoMapPointRow this[int index] {
                get {
                    return ((JokasoMapPointRow)(this.Rows[index]));
                }
            }
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event JokasoMapPointRowChangeEventHandler JokasoMapPointRowChanging;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event JokasoMapPointRowChangeEventHandler JokasoMapPointRowChanged;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event JokasoMapPointRowChangeEventHandler JokasoMapPointRowDeleting;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event JokasoMapPointRowChangeEventHandler JokasoMapPointRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void AddJokasoMapPointRow(JokasoMapPointRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public JokasoMapPointRow AddJokasoMapPointRow(
                        string KensaIraiHoteiKbn, 
                        string KensaIraiHokenjoCd, 
                        string KensaIraiNendo, 
                        string KensaIraiRenban, 
                        string KensaIraiRowIndex, 
                        string JokasoSetchishaNm, 
                        string JokasoSetchiBashoAdr, 
                        string KensaKekkaKensaJoukyouKbn, 
                        string JokasoZenrinKeidoCd, 
                        string JokasoZenrinIdoCd, 
                        System.Guid MapPointStatusObjectID, 
                        System.Guid MapPointInfoObjectID, 
                        System.Guid MapPointSeqObjectID, 
                        System.Guid MapPointSeqObjectID_backcolor, 
                        int MapPointX, 
                        int MapPointY) {
                JokasoMapPointRow rowJokasoMapPointRow = ((JokasoMapPointRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        KensaIraiHoteiKbn,
                        KensaIraiHokenjoCd,
                        KensaIraiNendo,
                        KensaIraiRenban,
                        KensaIraiRowIndex,
                        JokasoSetchishaNm,
                        JokasoSetchiBashoAdr,
                        KensaKekkaKensaJoukyouKbn,
                        JokasoZenrinKeidoCd,
                        JokasoZenrinIdoCd,
                        MapPointStatusObjectID,
                        MapPointInfoObjectID,
                        MapPointSeqObjectID,
                        MapPointSeqObjectID_backcolor,
                        MapPointX,
                        MapPointY};
                rowJokasoMapPointRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowJokasoMapPointRow);
                return rowJokasoMapPointRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public JokasoMapPointRow FindByKensaIraiRenbanKensaIraiNendoKensaIraiHokenjoCdKensaIraiHoteiKbn(string KensaIraiRenban, string KensaIraiNendo, string KensaIraiHokenjoCd, string KensaIraiHoteiKbn) {
                return ((JokasoMapPointRow)(this.Rows.Find(new object[] {
                            KensaIraiRenban,
                            KensaIraiNendo,
                            KensaIraiHokenjoCd,
                            KensaIraiHoteiKbn})));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public override global::System.Data.DataTable Clone() {
                JokasoMapPointDataTable cln = ((JokasoMapPointDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Data.DataTable CreateInstance() {
                return new JokasoMapPointDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal void InitVars() {
                this.columnKensaIraiHoteiKbn = base.Columns["KensaIraiHoteiKbn"];
                this.columnKensaIraiHokenjoCd = base.Columns["KensaIraiHokenjoCd"];
                this.columnKensaIraiNendo = base.Columns["KensaIraiNendo"];
                this.columnKensaIraiRenban = base.Columns["KensaIraiRenban"];
                this.columnKensaIraiRowIndex = base.Columns["KensaIraiRowIndex"];
                this.columnJokasoSetchishaNm = base.Columns["JokasoSetchishaNm"];
                this.columnJokasoSetchiBashoAdr = base.Columns["JokasoSetchiBashoAdr"];
                this.columnKensaKekkaKensaJoukyouKbn = base.Columns["KensaKekkaKensaJoukyouKbn"];
                this.columnJokasoZenrinKeidoCd = base.Columns["JokasoZenrinKeidoCd"];
                this.columnJokasoZenrinIdoCd = base.Columns["JokasoZenrinIdoCd"];
                this.columnMapPointStatusObjectID = base.Columns["MapPointStatusObjectID"];
                this.columnMapPointInfoObjectID = base.Columns["MapPointInfoObjectID"];
                this.columnMapPointSeqObjectID = base.Columns["MapPointSeqObjectID"];
                this.columnMapPointSeqObjectID_backcolor = base.Columns["MapPointSeqObjectID_backcolor"];
                this.columnMapPointX = base.Columns["MapPointX"];
                this.columnMapPointY = base.Columns["MapPointY"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            private void InitClass() {
                this.columnKensaIraiHoteiKbn = new global::System.Data.DataColumn("KensaIraiHoteiKbn", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnKensaIraiHoteiKbn);
                this.columnKensaIraiHokenjoCd = new global::System.Data.DataColumn("KensaIraiHokenjoCd", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnKensaIraiHokenjoCd);
                this.columnKensaIraiNendo = new global::System.Data.DataColumn("KensaIraiNendo", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnKensaIraiNendo);
                this.columnKensaIraiRenban = new global::System.Data.DataColumn("KensaIraiRenban", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnKensaIraiRenban);
                this.columnKensaIraiRowIndex = new global::System.Data.DataColumn("KensaIraiRowIndex", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnKensaIraiRowIndex);
                this.columnJokasoSetchishaNm = new global::System.Data.DataColumn("JokasoSetchishaNm", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnJokasoSetchishaNm);
                this.columnJokasoSetchiBashoAdr = new global::System.Data.DataColumn("JokasoSetchiBashoAdr", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnJokasoSetchiBashoAdr);
                this.columnKensaKekkaKensaJoukyouKbn = new global::System.Data.DataColumn("KensaKekkaKensaJoukyouKbn", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnKensaKekkaKensaJoukyouKbn);
                this.columnJokasoZenrinKeidoCd = new global::System.Data.DataColumn("JokasoZenrinKeidoCd", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnJokasoZenrinKeidoCd);
                this.columnJokasoZenrinIdoCd = new global::System.Data.DataColumn("JokasoZenrinIdoCd", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnJokasoZenrinIdoCd);
                this.columnMapPointStatusObjectID = new global::System.Data.DataColumn("MapPointStatusObjectID", typeof(global::System.Guid), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnMapPointStatusObjectID);
                this.columnMapPointInfoObjectID = new global::System.Data.DataColumn("MapPointInfoObjectID", typeof(global::System.Guid), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnMapPointInfoObjectID);
                this.columnMapPointSeqObjectID = new global::System.Data.DataColumn("MapPointSeqObjectID", typeof(global::System.Guid), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnMapPointSeqObjectID);
                this.columnMapPointSeqObjectID_backcolor = new global::System.Data.DataColumn("MapPointSeqObjectID_backcolor", typeof(global::System.Guid), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnMapPointSeqObjectID_backcolor);
                this.columnMapPointX = new global::System.Data.DataColumn("MapPointX", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnMapPointX);
                this.columnMapPointY = new global::System.Data.DataColumn("MapPointY", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnMapPointY);
                this.Constraints.Add(new global::System.Data.UniqueConstraint("Constraint1", new global::System.Data.DataColumn[] {
                                this.columnKensaIraiRenban,
                                this.columnKensaIraiNendo,
                                this.columnKensaIraiHokenjoCd,
                                this.columnKensaIraiHoteiKbn}, true));
                this.columnKensaIraiHoteiKbn.AllowDBNull = false;
                this.columnKensaIraiHoteiKbn.ReadOnly = true;
                this.columnKensaIraiHoteiKbn.MaxLength = 1;
                this.columnKensaIraiHokenjoCd.AllowDBNull = false;
                this.columnKensaIraiHokenjoCd.ReadOnly = true;
                this.columnKensaIraiHokenjoCd.MaxLength = 2;
                this.columnKensaIraiNendo.AllowDBNull = false;
                this.columnKensaIraiNendo.ReadOnly = true;
                this.columnKensaIraiNendo.MaxLength = 4;
                this.columnKensaIraiRenban.AllowDBNull = false;
                this.columnKensaIraiRenban.ReadOnly = true;
                this.columnKensaIraiRenban.MaxLength = 6;
                this.columnJokasoSetchishaNm.ReadOnly = true;
                this.columnJokasoSetchishaNm.MaxLength = 60;
                this.columnJokasoSetchiBashoAdr.ReadOnly = true;
                this.columnJokasoSetchiBashoAdr.MaxLength = 80;
                this.columnKensaKekkaKensaJoukyouKbn.ReadOnly = true;
                this.columnKensaKekkaKensaJoukyouKbn.MaxLength = 3;
                this.columnJokasoZenrinKeidoCd.ReadOnly = true;
                this.columnJokasoZenrinKeidoCd.MaxLength = 10;
                this.columnJokasoZenrinIdoCd.ReadOnly = true;
                this.columnJokasoZenrinIdoCd.MaxLength = 10;
                this.columnMapPointStatusObjectID.Caption = "ObjectID";
                this.columnMapPointInfoObjectID.Caption = "InfoObjectID";
                this.columnMapPointSeqObjectID.Caption = "SeqObjectID";
                this.columnMapPointSeqObjectID_backcolor.Caption = "SeqObjectID_backcolor";
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public JokasoMapPointRow NewJokasoMapPointRow() {
                return ((JokasoMapPointRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new JokasoMapPointRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Type GetRowType() {
                return typeof(JokasoMapPointRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.JokasoMapPointRowChanged != null)) {
                    this.JokasoMapPointRowChanged(this, new JokasoMapPointRowChangeEvent(((JokasoMapPointRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.JokasoMapPointRowChanging != null)) {
                    this.JokasoMapPointRowChanging(this, new JokasoMapPointRowChangeEvent(((JokasoMapPointRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.JokasoMapPointRowDeleted != null)) {
                    this.JokasoMapPointRowDeleted(this, new JokasoMapPointRowChangeEvent(((JokasoMapPointRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.JokasoMapPointRowDeleting != null)) {
                    this.JokasoMapPointRowDeleting(this, new JokasoMapPointRowChangeEvent(((JokasoMapPointRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void RemoveJokasoMapPointRow(JokasoMapPointRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                MapPointDataSet ds = new MapPointDataSet();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "JokasoMapPointDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class JokasoMapPointRow : global::System.Data.DataRow {
            
            private JokasoMapPointDataTable tableJokasoMapPoint;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal JokasoMapPointRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableJokasoMapPoint = ((JokasoMapPointDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string KensaIraiHoteiKbn {
                get {
                    return ((string)(this[this.tableJokasoMapPoint.KensaIraiHoteiKbnColumn]));
                }
                set {
                    this[this.tableJokasoMapPoint.KensaIraiHoteiKbnColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string KensaIraiHokenjoCd {
                get {
                    return ((string)(this[this.tableJokasoMapPoint.KensaIraiHokenjoCdColumn]));
                }
                set {
                    this[this.tableJokasoMapPoint.KensaIraiHokenjoCdColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string KensaIraiNendo {
                get {
                    return ((string)(this[this.tableJokasoMapPoint.KensaIraiNendoColumn]));
                }
                set {
                    this[this.tableJokasoMapPoint.KensaIraiNendoColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string KensaIraiRenban {
                get {
                    return ((string)(this[this.tableJokasoMapPoint.KensaIraiRenbanColumn]));
                }
                set {
                    this[this.tableJokasoMapPoint.KensaIraiRenbanColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string KensaIraiRowIndex {
                get {
                    try {
                        return ((string)(this[this.tableJokasoMapPoint.KensaIraiRowIndexColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'JokasoMapPoint\' にある列 \'KensaIraiRowIndex\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tableJokasoMapPoint.KensaIraiRowIndexColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string JokasoSetchishaNm {
                get {
                    try {
                        return ((string)(this[this.tableJokasoMapPoint.JokasoSetchishaNmColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'JokasoMapPoint\' にある列 \'JokasoSetchishaNm\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tableJokasoMapPoint.JokasoSetchishaNmColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string JokasoSetchiBashoAdr {
                get {
                    try {
                        return ((string)(this[this.tableJokasoMapPoint.JokasoSetchiBashoAdrColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'JokasoMapPoint\' にある列 \'JokasoSetchiBashoAdr\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tableJokasoMapPoint.JokasoSetchiBashoAdrColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string KensaKekkaKensaJoukyouKbn {
                get {
                    try {
                        return ((string)(this[this.tableJokasoMapPoint.KensaKekkaKensaJoukyouKbnColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'JokasoMapPoint\' にある列 \'KensaKekkaKensaJoukyouKbn\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tableJokasoMapPoint.KensaKekkaKensaJoukyouKbnColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string JokasoZenrinKeidoCd {
                get {
                    try {
                        return ((string)(this[this.tableJokasoMapPoint.JokasoZenrinKeidoCdColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'JokasoMapPoint\' にある列 \'JokasoZenrinKeidoCd\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tableJokasoMapPoint.JokasoZenrinKeidoCdColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public string JokasoZenrinIdoCd {
                get {
                    try {
                        return ((string)(this[this.tableJokasoMapPoint.JokasoZenrinIdoCdColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'JokasoMapPoint\' にある列 \'JokasoZenrinIdoCd\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tableJokasoMapPoint.JokasoZenrinIdoCdColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public System.Guid MapPointStatusObjectID {
                get {
                    try {
                        return ((global::System.Guid)(this[this.tableJokasoMapPoint.MapPointStatusObjectIDColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'JokasoMapPoint\' にある列 \'MapPointStatusObjectID\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tableJokasoMapPoint.MapPointStatusObjectIDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public System.Guid MapPointInfoObjectID {
                get {
                    try {
                        return ((global::System.Guid)(this[this.tableJokasoMapPoint.MapPointInfoObjectIDColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'JokasoMapPoint\' にある列 \'MapPointInfoObjectID\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tableJokasoMapPoint.MapPointInfoObjectIDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public System.Guid MapPointSeqObjectID {
                get {
                    try {
                        return ((global::System.Guid)(this[this.tableJokasoMapPoint.MapPointSeqObjectIDColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'JokasoMapPoint\' にある列 \'MapPointSeqObjectID\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tableJokasoMapPoint.MapPointSeqObjectIDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public System.Guid MapPointSeqObjectID_backcolor {
                get {
                    try {
                        return ((global::System.Guid)(this[this.tableJokasoMapPoint.MapPointSeqObjectID_backcolorColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'JokasoMapPoint\' にある列 \'MapPointSeqObjectID_backcolor\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tableJokasoMapPoint.MapPointSeqObjectID_backcolorColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int MapPointX {
                get {
                    try {
                        return ((int)(this[this.tableJokasoMapPoint.MapPointXColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'JokasoMapPoint\' にある列 \'MapPointX\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tableJokasoMapPoint.MapPointXColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int MapPointY {
                get {
                    try {
                        return ((int)(this[this.tableJokasoMapPoint.MapPointYColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("テーブル \'JokasoMapPoint\' にある列 \'MapPointY\' の値は DBNull です。", e);
                    }
                }
                set {
                    this[this.tableJokasoMapPoint.MapPointYColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsKensaIraiRowIndexNull() {
                return this.IsNull(this.tableJokasoMapPoint.KensaIraiRowIndexColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetKensaIraiRowIndexNull() {
                this[this.tableJokasoMapPoint.KensaIraiRowIndexColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsJokasoSetchishaNmNull() {
                return this.IsNull(this.tableJokasoMapPoint.JokasoSetchishaNmColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetJokasoSetchishaNmNull() {
                this[this.tableJokasoMapPoint.JokasoSetchishaNmColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsJokasoSetchiBashoAdrNull() {
                return this.IsNull(this.tableJokasoMapPoint.JokasoSetchiBashoAdrColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetJokasoSetchiBashoAdrNull() {
                this[this.tableJokasoMapPoint.JokasoSetchiBashoAdrColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsKensaKekkaKensaJoukyouKbnNull() {
                return this.IsNull(this.tableJokasoMapPoint.KensaKekkaKensaJoukyouKbnColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetKensaKekkaKensaJoukyouKbnNull() {
                this[this.tableJokasoMapPoint.KensaKekkaKensaJoukyouKbnColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsJokasoZenrinKeidoCdNull() {
                return this.IsNull(this.tableJokasoMapPoint.JokasoZenrinKeidoCdColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetJokasoZenrinKeidoCdNull() {
                this[this.tableJokasoMapPoint.JokasoZenrinKeidoCdColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsJokasoZenrinIdoCdNull() {
                return this.IsNull(this.tableJokasoMapPoint.JokasoZenrinIdoCdColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetJokasoZenrinIdoCdNull() {
                this[this.tableJokasoMapPoint.JokasoZenrinIdoCdColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsMapPointStatusObjectIDNull() {
                return this.IsNull(this.tableJokasoMapPoint.MapPointStatusObjectIDColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetMapPointStatusObjectIDNull() {
                this[this.tableJokasoMapPoint.MapPointStatusObjectIDColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsMapPointInfoObjectIDNull() {
                return this.IsNull(this.tableJokasoMapPoint.MapPointInfoObjectIDColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetMapPointInfoObjectIDNull() {
                this[this.tableJokasoMapPoint.MapPointInfoObjectIDColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsMapPointSeqObjectIDNull() {
                return this.IsNull(this.tableJokasoMapPoint.MapPointSeqObjectIDColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetMapPointSeqObjectIDNull() {
                this[this.tableJokasoMapPoint.MapPointSeqObjectIDColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsMapPointSeqObjectID_backcolorNull() {
                return this.IsNull(this.tableJokasoMapPoint.MapPointSeqObjectID_backcolorColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetMapPointSeqObjectID_backcolorNull() {
                this[this.tableJokasoMapPoint.MapPointSeqObjectID_backcolorColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsMapPointXNull() {
                return this.IsNull(this.tableJokasoMapPoint.MapPointXColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetMapPointXNull() {
                this[this.tableJokasoMapPoint.MapPointXColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool IsMapPointYNull() {
                return this.IsNull(this.tableJokasoMapPoint.MapPointYColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void SetMapPointYNull() {
                this[this.tableJokasoMapPoint.MapPointYColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public class JokasoMapPointRowChangeEvent : global::System.EventArgs {
            
            private JokasoMapPointRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public JokasoMapPointRowChangeEvent(JokasoMapPointRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public JokasoMapPointRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591