using System;
using System.Collections.Generic;
using System.Data;
using System.Reflection;
using System.Text;
using Zynas.Framework.Core.Base.ApplicationLogic;
using Zynas.Framework.Core.Common.DataAccess;
using Zynas.Framework.Core.Generic.BusinessLogic;
using Zynas.Framework.Utility;

namespace FukjBizSystem.Application.ApplicationLogic.Generic.StdShosai
{
    #region 入力インターフェイス定義
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <history>
    /// 日付　　　　担当者　　　内容
    /// 2014/08/28　habu　　    新規作成
    /// </history>
    public interface IFormLoadALInput : IBseALInput , IStdFilteredGetDataBLInput
    {

    }
    #endregion

    #region 入力クラス定義
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <history>
    /// 日付　　　　担当者　　　内容
    /// 2014/08/28　habu　　    新規作成
    /// </history>
    class FormLoadALInput : IBseALInputImpl, IFormLoadALInput
    {
        /// <summary>
        /// Type of TableAdapter. Use typeof(XXXTableAdapter)
        /// </summary>
        public Type TableAdapterType { get; set; }

        /// <summary>
        /// Type of DataTable. Use typeof(XXXDataTable)
        /// </summary>
        public Type DataTableType { get; set; }

        /// <summary>
        /// Where claus generated by AddXXXmethods
        /// </summary>
        public string WhereStr
        {
            get
            {
                return whereBuf.ToString();
            }
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="colName"></param>
        /// <param name="value"></param>
        public void AddEqualCond(string colName, object value)
        {
            QueryBuilderUtility.AddEqualCond(whereBuf, colName, value);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="colName"></param>
        /// <param name="value"></param>
        public void AddGreaterCond(string colName, object value)
        {
            QueryBuilderUtility.AddGreaterCond(whereBuf, colName, value);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="colName"></param>
        /// <param name="value"></param>
        public void AddGreaterEqualCond(string colName, object value)
        {
            QueryBuilderUtility.AddGreaterEqualCond(whereBuf, colName, value);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="colName"></param>
        /// <param name="value"></param>
        public void AddLesserCond(string colName, object value)
        {
            QueryBuilderUtility.AddLesserCond(whereBuf, colName, value);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="colName"></param>
        /// <param name="value"></param>
        public void AddLesserEqualCond(string colName, object value)
        {
            QueryBuilderUtility.AddLesserEqualCond(whereBuf, colName, value);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="colName"></param>
        /// <param name="value"></param>
        public void AddNotEqualCond(string colName, object value)
        {
            QueryBuilderUtility.AddNotEqualCond(whereBuf, colName, value);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="colName"></param>
        /// <param name="value"></param>
        public void AddLikeCond(string colName, object value)
        {
            QueryBuilderUtility.AddLikeCond(whereBuf, colName, value);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="colName"></param>
        /// <param name="valueList">
        /// list of value placed in "IN(...)". 
        /// Array, List<T>, any other "foreachable" collection accepted />
        /// </param>
        public void AddInCond(string colName, IEnumerable<object> valueList)
        {
            QueryBuilderUtility.AddInCond(whereBuf, colName, valueList);
        }

        /// <summary>
        /// 
        /// </summary>
        private StringBuilder whereBuf = new StringBuilder();
    }
    #endregion

    #region 出力インターフェイス定義
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <history>
    /// 日付　　　　担当者　　　内容
    /// 2014/08/28　habu　　    新規作成
    /// </history>
    public interface IFormLoadALOutput
    {
        /// <summary>
        /// Select query result
        /// </summary>
        DataTable SearchDataTable { get; set; }
    }
    #endregion

    #region 出力クラス定義
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <history>
    /// 日付　　　　担当者　　　内容
    /// 2014/08/28　habu　　    新規作成
    /// </history>
    class FormLoadALOutput : IFormLoadALOutput
    {
        /// <summary>
        /// Select query result
        /// </summary>
        public DataTable SearchDataTable { get; set; }
    }
    #endregion

    #region クラス定義
    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <history>
    /// 日付　　　　担当者　　　内容
    /// 2014/08/28　habu　　    新規作成
    /// </history>
    class FormLoadApplicationLogic : BaseApplicationLogic<IFormLoadALInput, IFormLoadALOutput>
    {
        #region プロパティ

        /// <summary>
        /// 機能名
        /// </summary>
        private const string FunctionName = "StdList：FormLoad";

        #endregion

        #region コンストラクタ
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <history>
        /// 日付　　　　担当者　　　内容
        /// 2014/08/28　habu　　    新規作成
        /// </history>
        public FormLoadApplicationLogic()
        {

        }
        #endregion

        #region メソッド(protected)

        #region GetFunctionName
        /// <summary>
        /// 機能名取得
        /// </summary>
        /// <returns>機能名</returns>
        /// <history>
        /// 日付　　　　担当者　　　内容
        /// 2014/08/28　habu　　    新規作成
        /// </history>
        protected override string GetFunctionName()
        {
            return FunctionName;
        }
        #endregion

        #endregion

        #region メソッド(public)

        #region Execute
        /// <summary>
        /// 
        /// </summary>
        /// <param name="input"></param>
        /// <returns></returns>
        /// <history>
        /// 日付　　　　担当者　　　内容
        /// 2014/08/28　habu　　    新規作成
        /// </history>
        public override IFormLoadALOutput Execute(IFormLoadALInput input)
        {
            TraceLog.StartWrite(MethodInfo.GetCurrentMethod());

            // 出力クラスの実体作成
            IFormLoadALOutput output = new FormLoadALOutput();

            try
            {
                IStdFilteredGetDataBLOutput blOutput = new StdFilteredGetDataBusinessLogic().Execute(input);

                output.SearchDataTable = blOutput.GetDataTable;
            }
            catch
            {
                throw;
            }
            finally
            {
                TraceLog.EndWrite(MethodInfo.GetCurrentMethod());
            }

            return output;
        }
        #endregion

        #endregion
    }
    #endregion
}
